version: '3.8'

services:
        db:
                image: mariadb:10.8
                #image: jsurf/rpi-mariadb
                command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
                restart: always
                volumes:
                        - ${DB_ROOT:-./data/db}:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
        app:
                image: nextcloud:24
                restart: always
                ports:
                        - "127.0.0.1:8082:80"
                volumes:
                        # - ./data/www:/var/www/html
                        - ${WWW_ROOT:-./data/www}/data:/var/www/html/data
                        - ${WWW_ROOT:-./data/www}/config:/var/www/html/config
                        - ${WWW_ROOT:-./data/www}/custom_apps:/var/www/html/custom_apps
                        - ${WWW_ROOT:-./data/www}/themes:/var/www/html/themes
                environment:
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_HOST=db:3306
                        - NEXTCLOUD_TRUSTED_DOMAINS=nc.aoirint.com
                depends_on:
                        - db

