version: '3.8'

services:
  db:
    image: mariadb:10
    #image: jsurf/rpi-mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
      - ${DB_ROOT:-./volumes/mysql_data}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ${REDIS_ROOT:-./volumes/redis_data}:/data

  nextcloud:
    image: nextcloud:27
    restart: always
    volumes:
      # - ./data/www:/var/www/html
      - ${WWW_ROOT:-./volumes/nextcloud_www_data}/data:/var/www/html/data
      - ${WWW_ROOT:-./volumes/nextcloud_www_data}/config:/var/www/html/config
      - ${WWW_ROOT:-./volumes/nextcloud_www_data}/custom_apps:/var/www/html/custom_apps
      - ${WWW_ROOT:-./volumes/nextcloud_www_data}/themes:/var/www/html/themes
      - ./php.ini:/usr/local/etc/php/conf.d/additional_php.ini
      - ${FILES_RIKKA_ROOT:-./volumes/nextcloud_files_rikka}:/files/rikka
      - ${FILES_IRIS_ROOT:-./volumes/nextcloud_files_iris}:/files/iris
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db:3306
      - NEXTCLOUD_TRUSTED_DOMAINS=nc.aoirint.com
      - APACHE_BODY_LIMIT=10737418240 # 10GiB
      - PHP_MEMORY_LIMIT=512M # 512MB
    extra_hosts:
      - "minio.aoirint.com:${MINIO_AOIRINT_COM_IP_ADDRESS:?}"
    depends_on:
      - db
    logging:
      driver: fluentd
      options:
        tag: docker.nc_aoirint_com.nextcloud.{{.ID}}
        fluentd-async: "true"

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - nextcloud
    ports:
      - "127.0.0.1:8082:80"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx
    logging:
      driver: fluentd
      options:
        tag: docker.nc_aoirint_com.nginx.{{.ID}}
        fluentd-async: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
