version: '2'

volumes:
        app:

services:
        db:
                image: jsurf/rpi-mariadb
                restart: always
                volumes:
                        - /mnt/rachel/nextcloud/db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
        app:
                image: nextcloud
                ports:
                        - 8082:80
                volumes:
                        - /mnt/rachel/nextcloud/www:/var/www/html
                environment:
                        - NEXTCLOUD_TRUSTED_DOMAINS=nc.homelc0o0cl.ml
                restart: always
