version: '3'

services:
        db:
                image: jsurf/rpi-mariadb
                command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
                restart: always
                volumes:
                        - /mnt/rachel/nextcloud/db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
        app:
                image: nextcloud
                restart: always
                ports:
                        - "127.0.0.1:8082:80"
                volumes:
                        - /mnt/rachel/nextcloud/www:/var/www/html
                environment:
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_HOST=db:3306
                        - NEXTCLOUD_TRUSTED_DOMAINS=nc.homec0o0cl.ml

