version: '3.8'

services:
        db:
                image: mariadb:10.5
                #image: jsurf/rpi-mariadb
                command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
                restart: always
                volumes:
                        - /mnt/rosetta/nextcloud/db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
        app:
                image: nextcloud:21
                restart: always
                ports:
                        - "127.0.0.1:8082:80"
                volumes:
                        # - /mnt/rosetta/nextcloud/www:/var/www/html
                        - /mnt/rosetta/nextcloud/www/data:/var/www/html/data
                        - /mnt/rosetta/nextcloud/www/config:/var/www/html/config
                        - /mnt/rosetta/nextcloud/www/custom_apps:/var/www/html/custom_apps
                        - /mnt/rosetta/nextcloud/www/themes:/var/www/html/themes
                environment:
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_PASSWORD=nextcloud
                        - MYSQL_HOST=db:3306
                        - NEXTCLOUD_TRUSTED_DOMAINS=nc.homec0o0cl.ml
                depends_on:
                        - db

